server:
  port: 8081

spring:
  profiles:
    include:
      - api
      - event
  cloud:
    function:
      definition: process
    stream:
      function:
        bindings:
          process-in-0: input
      bindings:
        input:
          group: products
          destination: products