spring:
  cloud:
    stream:
      bindings:
        input:
          consumer:
            maxAttempts: 3 # 메시지 재처리 횟수 (default: 3)
            backOffInitialInterval: 300
            backOffMaxInterval: 500
      kafka:
        binder:
          configuration:
            deafult:
              key:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              value:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        bindings:
          input-in-0:
            consumer:
              ack-mode: BATCH
          input:
            consumer:
              enableDlq: true
---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.108.226.80:9092
---
spring:
  config:
    activate:
      on-profile: real
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.108.226.80:9092