apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-compose-2
  labels:
    app: product-compose
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-compose
  template:
    metadata:
      labels:
        app: product-compose
    spec:
      containers:
      - name: product-compose
        image: yhc94/msa-study-product-composite:latest
        imagePullPolicy: Always
        env:
        - name: "SPRING_PROFILES_ACTIVE"
          value: "local"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: product-compose
spec:
  selector:
    app: product-compose
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
