apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  type: LoadBalancer
status:
  loadBalancer: {}
