logging:
  level:
    root: info
spring:
  data:
    mongodb:
      uri: mongodb://adminuser:password123@127.0.0.1:30717/msa-study?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false