### Get Product By ID
GET http://{product-host}:{product-port}/products/1

### Get AlProducts
GET http://{product-host}:{product-port}/products/1

### Create Product
POST http://{product-host}:{product-port}/products
Content-Type: application/json

{
  "name": "TEST2",
  "weight": 1
}

### Delete Product By ID
DELETE http://{product-host}:{product-port}/products/5